language: bash
go:
- 1.3.3
- 1.4.2
- 1.5.1
- tip
- master
script:
- bash test.sh
- GOOS=linux GOARCH=amd64 go build -o rsaconfigcipher decrypt_files.go
- GOOS=windows GOARCH=amd64 go build -o rsaconfigcipher.exe decrypt_files.go
deploy:
  provider: releases
  api_key:
    secure: a0uZEIiWoruHLPajpvpXCl4cz6QXjJdOihz61lsQCmdrjb8zGh9XJ1maALQsjWcWt0/p1xUma3JmW2KisD/nW1kCzE8HRw5dFhEjf+Vo1aSyr52cNRd81I3fFGLdPICeQSwC06LgJLN5yFhKsKYM12daI8p34HddMoKyp28KM3mLNXpCY8iU2TTW5Cj9PS3Ps10jsPnG6QA8LOjiLaoqQGCqi5mesI/3aqZ8VpFbzcu1hQbDwtj9sY4HS1vi6byq/8KMs28SH/2BkJqXvkjMO8EKJyo9wa54j9qlgzhd7Pn4qj5fiFVuR4rnT66fwdSdfkzdLgxOuZVO9Q1BypP+d6FYhsUIIdMVsKqCexoeRQLeAvIhaRtTeIOHenFbL5V2WnabWda4QKZVBNRtjXRGPCKWfe8srx+lJMLgdo9OxaGknFJtclqbHPnb43w67O8NqNjT6lNlSr7jmxE5IYuf91XYmQ65d6GcRHD5iMcx0QhFiOUVxF14jEHTpvDl/m4HS/tTYi6fw0zdt+RzXYGsKu6vPts4RD2Sp3srj6DGYWUbBlGKVwjeZdq405fFz6srL9uBqSI8gctZ2ZGDl3LQ21BcwR8nludvZSRBgQFNjH4A4Nf8aMIC73sknOsAU6/X1AkwHVLiZRk4DQzDwg8sLJd6VT7nf3nIT7vMuELjqX8=
  file:
  - rsaconfigcipher
  - rsaconfigcipher.exe
  skip_cleanup: true
  on:
    repo: juusechec/RSAConfigCipher
    tags: true
